# Generated by Django 3.2.15 on 2022-11-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.book_author'),
        ),
    ]
