# Generated by Django 3.2.15 on 2022-12-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book_author',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='book_author',
        ),
    ]
