# Generated by Django 3.2.15 on 2022-12-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='age', to='blog.age_range'),
        ),
        migrations.AlterField(
            model_name='post',
            name='book_author',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='book_author',
        ),
    ]
