# Generated by Django 3.2.15 on 2022-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221204_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
